openapi: 3.0.0
info:
  title: GitHub API
  version: 1.0.0
  description: GitHub REST API for testing

servers:
  - url: https://api.github.com
    description: GitHub API

paths:
  /user:
    get:
      summary: Get authenticated user
      tags: [users]
      responses:
        '200':
          description: User information
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  login:
                    type: string
                  name:
                    type: string
                  email:
                    type: string
        '401':
          description: Unauthorized

  /users/{username}:
    get:
      summary: Get user by username
      tags: [users]
      parameters:
        - name: username
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: User information
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  login:
                    type: string
                  name:
                    type: string
                  public_repos:
                    type: integer
        '404':
          description: User not found

  /repos/{owner}/{repo}:
    get:
      summary: Get repository
      tags: [repos]
      parameters:
        - name: owner
          in: path
          required: true
          schema:
            type: string
        - name: repo
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Repository information
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  full_name:
                    type: string
                  description:
                    type: string
                  stargazers_count:
                    type: integer
        '404':
          description: Repository not found 