openapi: 3.0.0
info:
  title: Local API
  version: 1.0.0
  description: Local development API

servers:
  - url: http://localhost:8000
    description: Local development server

paths:
  /api/items:
    get:
      summary: Get all items
      tags: [items]
      responses:
        '200':
          description: List of items
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
                    price:
                      type: number
    
    post:
      summary: Create a new item
      tags: [items]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                price:
                  type: number
              required:
                - name
                - price
      responses:
        '201':
          description: Item created successfully
        '400':
          description: Invalid input data

  /api/items/{id}:
    get:
      summary: Get item by ID
      tags: [items]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Item details
        '404':
          description: Item not found 